🔙 Revert "✨ Add workaround for `mas signin` no longer being supported"
`mas account` also no longer works 😢

> bramus in ~ λ mas account
> Error: This command is not supported on this macOS version due to changes in macOS. For more information see: https://github.com/mas-cli/mas#known-issues